aapiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
  namespace: webapps
  labels:
    app: bloggingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bloggingapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: bloggingapp
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-13T08:41:41Z"
    spec:
      containers:
      - name: bloggingapp
        image: ahmedrafat/blogging-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
